// Generated by pnpm db:types from versioned migrations. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = {
  public: {
    Tables: {
      cities: {
        Row: {
          id: string;
          country_id: string;
          name: string;
          slug: string;
          latitude: number | null;
          longitude: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          country_id: string;
          name: string;
          slug: string;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          country_id?: string;
          name?: string;
          slug?: string;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "cities_country_id_fkey"; columns: ["country_id"]; isOneToOne: false; referencedRelation: "countries"; referencedColumns: ["id"] },
        ];
      };
      countries: {
        Row: {
          id: string;
          name: string;
          code: string;
          slug: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          code: string;
          slug: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          code?: string;
          slug?: string;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      hotels: {
        Row: {
          id: string;
          name: string;
          slug: string;
          brand: string | null;
          city_id: string;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          description: string | null;
          rating: number | null;
          recommended_family: boolean;
          recommended_business: boolean;
          recommended_leisure: boolean;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
          review_text: string | null;
          cover_photo_id: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          brand?: string | null;
          city_id: string;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          rating?: number | null;
          recommended_family?: boolean;
          recommended_business?: boolean;
          recommended_leisure?: boolean;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
          review_text?: string | null;
          cover_photo_id?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          brand?: string | null;
          city_id?: string;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          rating?: number | null;
          recommended_family?: boolean;
          recommended_business?: boolean;
          recommended_leisure?: boolean;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
          review_text?: string | null;
          cover_photo_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "hotels_city_id_fkey"; columns: ["city_id"]; isOneToOne: false; referencedRelation: "cities"; referencedColumns: ["id"] },
          { foreignKeyName: "hotels_cover_photo_id_fkey"; columns: ["cover_photo_id"]; isOneToOne: false; referencedRelation: "photos"; referencedColumns: ["id"] },
        ];
      };
      import_batches: {
        Row: {
          id: string;
          created_at: string;
          source_name: string | null;
          total_files: number;
          eligible_files: number;
          skipped_personal: number;
          imported: number;
          status: string;
        };
        Insert: {
          id?: string;
          created_at?: string;
          source_name?: string | null;
          total_files?: number;
          eligible_files?: number;
          skipped_personal?: number;
          imported?: number;
          status?: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          source_name?: string | null;
          total_files?: number;
          eligible_files?: number;
          skipped_personal?: number;
          imported?: number;
          status?: string;
        };
        Relationships: [
        ];
      };
      import_items: {
        Row: {
          id: string;
          import_batch_id: string | null;
          filename: string;
          file_hash: string;
          file_size: number;
          classification: string;
          state: string;
          multipart_id: string | null;
          claim_token: string | null;
          lease_until: string | null;
          error: string | null;
          created_at: string;
          updated_at: string;
          context: string;
          hotel_id: string | null;
        };
        Insert: {
          id: string;
          import_batch_id?: string | null;
          filename: string;
          file_hash: string;
          file_size: number;
          classification: string;
          state?: string;
          multipart_id?: string | null;
          claim_token?: string | null;
          lease_until?: string | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
          context?: string;
          hotel_id?: string | null;
        };
        Update: {
          id?: string;
          import_batch_id?: string | null;
          filename?: string;
          file_hash?: string;
          file_size?: number;
          classification?: string;
          state?: string;
          multipart_id?: string | null;
          claim_token?: string | null;
          lease_until?: string | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
          context?: string;
          hotel_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "import_items_hotel_id_fkey"; columns: ["hotel_id"]; isOneToOne: false; referencedRelation: "hotels"; referencedColumns: ["id"] },
          { foreignKeyName: "import_items_import_batch_id_fkey"; columns: ["import_batch_id"]; isOneToOne: false; referencedRelation: "import_batches"; referencedColumns: ["id"] },
        ];
      };
      locations: {
        Row: {
          id: string;
          city_id: string;
          name: string;
          slug: string;
          latitude: number | null;
          longitude: number | null;
          description: string | null;
          cover_photo_id: string | null;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          city_id: string;
          name: string;
          slug: string;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          city_id?: string;
          name?: string;
          slug?: string;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "locations_city_id_fkey"; columns: ["city_id"]; isOneToOne: false; referencedRelation: "cities"; referencedColumns: ["id"] },
          { foreignKeyName: "locations_cover_photo_fk"; columns: ["cover_photo_id"]; isOneToOne: false; referencedRelation: "photos"; referencedColumns: ["id"] },
        ];
      };
      photos: {
        Row: {
          id: string;
          filename: string;
          storage_key: string;
          file_hash: string;
          width: number;
          height: number;
          file_size: number;
          classification: string;
          context: string;
          featured: boolean;
          caption: string | null;
          description: string | null;
          status: string;
          editorial_order: number | null;
          trip_id: string | null;
          location_id: string | null;
          import_batch_id: string | null;
          processing_status: string;
          captured_at: string | null;
          captured_at_offset_minutes: number | null;
          latitude: number | null;
          longitude: number | null;
          camera_make: string | null;
          camera_model: string | null;
          lens: string | null;
          focal_length: number | null;
          aperture: number | null;
          shutter_speed: string | null;
          iso: number | null;
          created_at: string;
          updated_at: string;
          derivative_profile: number;
          hotel_id: string | null;
        };
        Insert: {
          id?: string;
          filename: string;
          storage_key: string;
          file_hash: string;
          width: number;
          height: number;
          file_size: number;
          classification: string;
          context: string;
          featured?: boolean;
          caption?: string | null;
          description?: string | null;
          status?: string;
          editorial_order?: number | null;
          trip_id?: string | null;
          location_id?: string | null;
          import_batch_id?: string | null;
          processing_status?: string;
          captured_at?: string | null;
          captured_at_offset_minutes?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          camera_make?: string | null;
          camera_model?: string | null;
          lens?: string | null;
          focal_length?: number | null;
          aperture?: number | null;
          shutter_speed?: string | null;
          iso?: number | null;
          created_at?: string;
          updated_at?: string;
          derivative_profile?: number;
          hotel_id?: string | null;
        };
        Update: {
          id?: string;
          filename?: string;
          storage_key?: string;
          file_hash?: string;
          width?: number;
          height?: number;
          file_size?: number;
          classification?: string;
          context?: string;
          featured?: boolean;
          caption?: string | null;
          description?: string | null;
          status?: string;
          editorial_order?: number | null;
          trip_id?: string | null;
          location_id?: string | null;
          import_batch_id?: string | null;
          processing_status?: string;
          captured_at?: string | null;
          captured_at_offset_minutes?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          camera_make?: string | null;
          camera_model?: string | null;
          lens?: string | null;
          focal_length?: number | null;
          aperture?: number | null;
          shutter_speed?: string | null;
          iso?: number | null;
          created_at?: string;
          updated_at?: string;
          derivative_profile?: number;
          hotel_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "photo_trip_location_membership"; columns: ["trip_id","location_id"]; isOneToOne: false; referencedRelation: "trip_locations"; referencedColumns: ["trip_id","location_id"] },
          { foreignKeyName: "photos_hotel_id_fkey"; columns: ["hotel_id"]; isOneToOne: false; referencedRelation: "hotels"; referencedColumns: ["id"] },
          { foreignKeyName: "photos_import_batch_id_fkey"; columns: ["import_batch_id"]; isOneToOne: false; referencedRelation: "import_batches"; referencedColumns: ["id"] },
          { foreignKeyName: "photos_location_id_fkey"; columns: ["location_id"]; isOneToOne: false; referencedRelation: "locations"; referencedColumns: ["id"] },
          { foreignKeyName: "photos_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      stays: {
        Row: {
          id: string;
          hotel_id: string;
          trip_id: string | null;
          check_in: string | null;
          check_out: string | null;
          internal_notes: string | null;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          hotel_id: string;
          trip_id?: string | null;
          check_in?: string | null;
          check_out?: string | null;
          internal_notes?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          hotel_id?: string;
          trip_id?: string | null;
          check_in?: string | null;
          check_out?: string | null;
          internal_notes?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "stays_hotel_id_fkey"; columns: ["hotel_id"]; isOneToOne: false; referencedRelation: "hotels"; referencedColumns: ["id"] },
          { foreignKeyName: "stays_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      trip_cities: {
        Row: {
          trip_id: string;
          city_id: string;
          sequence: number | null;
        };
        Insert: {
          trip_id: string;
          city_id: string;
          sequence?: number | null;
        };
        Update: {
          trip_id?: string;
          city_id?: string;
          sequence?: number | null;
        };
        Relationships: [
          { foreignKeyName: "trip_cities_city_id_fkey"; columns: ["city_id"]; isOneToOne: false; referencedRelation: "cities"; referencedColumns: ["id"] },
          { foreignKeyName: "trip_cities_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      trip_locations: {
        Row: {
          trip_id: string;
          location_id: string;
          sequence: number | null;
          visited_at: string | null;
        };
        Insert: {
          trip_id: string;
          location_id: string;
          sequence?: number | null;
          visited_at?: string | null;
        };
        Update: {
          trip_id?: string;
          location_id?: string;
          sequence?: number | null;
          visited_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "trip_locations_location_id_fkey"; columns: ["location_id"]; isOneToOne: false; referencedRelation: "locations"; referencedColumns: ["id"] },
          { foreignKeyName: "trip_locations_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      trips: {
        Row: {
          id: string;
          title: string;
          slug: string;
          start_date: string | null;
          end_date: string | null;
          purpose: string | null;
          description: string | null;
          cover_photo_id: string | null;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          start_date?: string | null;
          end_date?: string | null;
          purpose?: string | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          start_date?: string | null;
          end_date?: string | null;
          purpose?: string | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "trips_cover_photo_fk"; columns: ["cover_photo_id"]; isOneToOne: false; referencedRelation: "photos"; referencedColumns: ["id"] },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      admin_begin_photo_delete: { Args: { p_id: string | null; p_token: string | null; }; Returns: undefined };
      admin_claim_photo_import: { Args: { p_id: string | null; p_token: string | null; p_phase: string | null; }; Returns: undefined };
      admin_create_city: { Args: { p_name: string | null; p_slug: string | null; p_country_id?: string | null; p_country_name?: string | null; p_country_code?: string | null; p_country_slug?: string | null; p_latitude?: number | null; p_longitude?: number | null; }; Returns: string };
      admin_create_import_batch: { Args: { p_id: string | null; p_source_name: string | null; p_total: number | null; p_eligible: number | null; p_skipped: number | null; }; Returns: string };
      admin_delete_trip: { Args: { p_trip_id: string | null; }; Returns: undefined };
      admin_fail_photo_delete: { Args: { p_id: string | null; p_token: string | null; }; Returns: undefined };
      admin_fail_photo_import: { Args: { p_id: string | null; p_token: string | null; p_cleanup_ok: boolean | null; }; Returns: undefined };
      admin_finalize_photo_import: { Args: { p_id: string | null; p_token: string | null; p_metadata: Json | null; }; Returns: string };
      admin_finish_import_batch: { Args: { p_id: string | null; p_failed?: boolean | null; }; Returns: undefined };
      admin_finish_photo_delete: { Args: { p_id: string | null; p_token: string | null; }; Returns: undefined };
      admin_mark_photo_upload: { Args: { p_id: string | null; p_token: string | null; p_multipart_id: string | null; }; Returns: undefined };
      admin_remove_trip_city: { Args: { p_trip_id: string | null; p_city_id: string | null; }; Returns: undefined };
      admin_remove_trip_location: { Args: { p_trip_id: string | null; p_location_id: string | null; }; Returns: undefined };
      admin_reserve_context_photo_import: { Args: { p_id: string | null; p_batch_id: string | null; p_filename: string | null; p_hash: string | null; p_size: number | null; p_classification: string | null; p_context: string | null; p_hotel_id?: string | null; }; Returns: string };
      admin_reserve_photo_import: { Args: { p_id: string | null; p_batch_id: string | null; p_filename: string | null; p_hash: string | null; p_size: number | null; p_classification: string | null; }; Returns: string };
      admin_save_hotel: { Args: { p_id: string | null; p_record: Json | null; }; Returns: string };
      admin_save_location: { Args: { p_id: string | null; p_city_id: string | null; p_name: string | null; p_slug: string | null; p_latitude?: number | null; p_longitude?: number | null; p_description?: string | null; p_status?: string | null; p_editorial_order?: number | null; p_trip_id?: string | null; }; Returns: string };
      admin_save_stay: { Args: { p_id: string | null; p_record: Json | null; }; Returns: string };
      admin_set_trip_city: { Args: { p_trip_id: string | null; p_city_id: string | null; p_sequence?: number | null; }; Returns: undefined };
      admin_set_trip_location: { Args: { p_trip_id: string | null; p_location_id: string | null; p_sequence?: number | null; p_visited_at?: string | null; }; Returns: undefined };
      city_is_singapore: { Args: { p_city_id: string | null; }; Returns: boolean };
      is_admin: { Args: Record<string, never>; Returns: boolean };
      public_archive_covers: { Args: { p_parent_ids: string[] | null; p_kind: string | null; }; Returns: { parent_id: string; photo_id: string }[] };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
