// Generated by pnpm db:types from versioned migrations. Do not edit by hand.
export type Database = {
  public: {
    Tables: {
      cities: {
        Row: {
          id: string;
          country_id: string;
          name: string;
          slug: string;
          latitude: number | null;
          longitude: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          country_id: string;
          name: string;
          slug: string;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          country_id?: string;
          name?: string;
          slug?: string;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "cities_country_id_fkey"; columns: ["country_id"]; isOneToOne: false; referencedRelation: "countries"; referencedColumns: ["id"] },
        ];
      };
      countries: {
        Row: {
          id: string;
          name: string;
          code: string;
          slug: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          code: string;
          slug: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          code?: string;
          slug?: string;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      hotels: {
        Row: {
          id: string;
          name: string;
          slug: string;
          brand: string | null;
          city_id: string;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          description: string | null;
          rating: number | null;
          recommended_family: boolean;
          recommended_business: boolean;
          recommended_leisure: boolean;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          brand?: string | null;
          city_id: string;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          rating?: number | null;
          recommended_family?: boolean;
          recommended_business?: boolean;
          recommended_leisure?: boolean;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          brand?: string | null;
          city_id?: string;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          rating?: number | null;
          recommended_family?: boolean;
          recommended_business?: boolean;
          recommended_leisure?: boolean;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "hotels_city_id_fkey"; columns: ["city_id"]; isOneToOne: false; referencedRelation: "cities"; referencedColumns: ["id"] },
        ];
      };
      import_batches: {
        Row: {
          id: string;
          created_at: string;
          source_name: string | null;
          total_files: number;
          eligible_files: number;
          skipped_personal: number;
          imported: number;
          status: string;
        };
        Insert: {
          id?: string;
          created_at?: string;
          source_name?: string | null;
          total_files?: number;
          eligible_files?: number;
          skipped_personal?: number;
          imported?: number;
          status?: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          source_name?: string | null;
          total_files?: number;
          eligible_files?: number;
          skipped_personal?: number;
          imported?: number;
          status?: string;
        };
        Relationships: [
        ];
      };
      locations: {
        Row: {
          id: string;
          city_id: string;
          name: string;
          slug: string;
          latitude: number | null;
          longitude: number | null;
          description: string | null;
          cover_photo_id: string | null;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          city_id: string;
          name: string;
          slug: string;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          city_id?: string;
          name?: string;
          slug?: string;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "locations_city_id_fkey"; columns: ["city_id"]; isOneToOne: false; referencedRelation: "cities"; referencedColumns: ["id"] },
          { foreignKeyName: "locations_cover_photo_fk"; columns: ["cover_photo_id"]; isOneToOne: false; referencedRelation: "photos"; referencedColumns: ["id"] },
        ];
      };
      photos: {
        Row: {
          id: string;
          filename: string;
          storage_key: string;
          file_hash: string;
          width: number;
          height: number;
          file_size: number;
          classification: string;
          context: string;
          featured: boolean;
          caption: string | null;
          description: string | null;
          status: string;
          editorial_order: number | null;
          trip_id: string | null;
          location_id: string | null;
          stay_id: string | null;
          import_batch_id: string | null;
          processing_status: string;
          captured_at: string | null;
          captured_at_offset_minutes: number | null;
          latitude: number | null;
          longitude: number | null;
          camera_make: string | null;
          camera_model: string | null;
          lens: string | null;
          focal_length: number | null;
          aperture: number | null;
          shutter_speed: string | null;
          iso: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          filename: string;
          storage_key: string;
          file_hash: string;
          width: number;
          height: number;
          file_size: number;
          classification: string;
          context: string;
          featured?: boolean;
          caption?: string | null;
          description?: string | null;
          status?: string;
          editorial_order?: number | null;
          trip_id?: string | null;
          location_id?: string | null;
          stay_id?: string | null;
          import_batch_id?: string | null;
          processing_status?: string;
          captured_at?: string | null;
          captured_at_offset_minutes?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          camera_make?: string | null;
          camera_model?: string | null;
          lens?: string | null;
          focal_length?: number | null;
          aperture?: number | null;
          shutter_speed?: string | null;
          iso?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          filename?: string;
          storage_key?: string;
          file_hash?: string;
          width?: number;
          height?: number;
          file_size?: number;
          classification?: string;
          context?: string;
          featured?: boolean;
          caption?: string | null;
          description?: string | null;
          status?: string;
          editorial_order?: number | null;
          trip_id?: string | null;
          location_id?: string | null;
          stay_id?: string | null;
          import_batch_id?: string | null;
          processing_status?: string;
          captured_at?: string | null;
          captured_at_offset_minutes?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          camera_make?: string | null;
          camera_model?: string | null;
          lens?: string | null;
          focal_length?: number | null;
          aperture?: number | null;
          shutter_speed?: string | null;
          iso?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "photo_trip_location_membership"; columns: ["trip_id","location_id"]; isOneToOne: false; referencedRelation: "trip_locations"; referencedColumns: ["trip_id","location_id"] },
          { foreignKeyName: "photos_import_batch_id_fkey"; columns: ["import_batch_id"]; isOneToOne: false; referencedRelation: "import_batches"; referencedColumns: ["id"] },
          { foreignKeyName: "photos_location_id_fkey"; columns: ["location_id"]; isOneToOne: false; referencedRelation: "locations"; referencedColumns: ["id"] },
          { foreignKeyName: "photos_stay_id_fkey"; columns: ["stay_id"]; isOneToOne: false; referencedRelation: "stays"; referencedColumns: ["id"] },
          { foreignKeyName: "photos_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      stays: {
        Row: {
          id: string;
          hotel_id: string;
          trip_id: string;
          check_in: string | null;
          check_out: string | null;
          room_type: string | null;
          purpose: string | null;
          rating: number | null;
          review_text: string | null;
          internal_notes: string | null;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          hotel_id: string;
          trip_id: string;
          check_in?: string | null;
          check_out?: string | null;
          room_type?: string | null;
          purpose?: string | null;
          rating?: number | null;
          review_text?: string | null;
          internal_notes?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          hotel_id?: string;
          trip_id?: string;
          check_in?: string | null;
          check_out?: string | null;
          room_type?: string | null;
          purpose?: string | null;
          rating?: number | null;
          review_text?: string | null;
          internal_notes?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "stays_hotel_id_fkey"; columns: ["hotel_id"]; isOneToOne: false; referencedRelation: "hotels"; referencedColumns: ["id"] },
          { foreignKeyName: "stays_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      trip_cities: {
        Row: {
          trip_id: string;
          city_id: string;
          sequence: number | null;
        };
        Insert: {
          trip_id: string;
          city_id: string;
          sequence?: number | null;
        };
        Update: {
          trip_id?: string;
          city_id?: string;
          sequence?: number | null;
        };
        Relationships: [
          { foreignKeyName: "trip_cities_city_id_fkey"; columns: ["city_id"]; isOneToOne: false; referencedRelation: "cities"; referencedColumns: ["id"] },
          { foreignKeyName: "trip_cities_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      trip_locations: {
        Row: {
          trip_id: string;
          location_id: string;
          sequence: number | null;
          visited_at: string | null;
        };
        Insert: {
          trip_id: string;
          location_id: string;
          sequence?: number | null;
          visited_at?: string | null;
        };
        Update: {
          trip_id?: string;
          location_id?: string;
          sequence?: number | null;
          visited_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "trip_locations_location_id_fkey"; columns: ["location_id"]; isOneToOne: false; referencedRelation: "locations"; referencedColumns: ["id"] },
          { foreignKeyName: "trip_locations_trip_id_fkey"; columns: ["trip_id"]; isOneToOne: false; referencedRelation: "trips"; referencedColumns: ["id"] },
        ];
      };
      trips: {
        Row: {
          id: string;
          title: string;
          slug: string;
          start_date: string | null;
          end_date: string | null;
          purpose: string | null;
          description: string | null;
          cover_photo_id: string | null;
          status: string;
          editorial_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          start_date?: string | null;
          end_date?: string | null;
          purpose?: string | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          start_date?: string | null;
          end_date?: string | null;
          purpose?: string | null;
          description?: string | null;
          cover_photo_id?: string | null;
          status?: string;
          editorial_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "trips_cover_photo_fk"; columns: ["cover_photo_id"]; isOneToOne: false; referencedRelation: "photos"; referencedColumns: ["id"] },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: { is_admin: { Args: Record<string, never>; Returns: boolean } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
