// Generate standard Supabase table types from the migrated PostgreSQL catalog.
// No hosted database secrets or Docker needed. Rerun whenever a migration changes.
import { writeFile, readFile } from 'node:fs/promises';
import { createTestDatabase } from '../tests/database';

const db = await createTestDatabase();
type Column = { table_name: string; column_name: string; data_type: string; is_nullable: string; column_default: string | null };
const { rows: columns } = await db.query<Column>(`select table_name,column_name,data_type,is_nullable,column_default
  from information_schema.columns where table_schema = 'public' order by table_name,ordinal_position`);
const tables = [...new Set(columns.map((column) => column.table_name))];
function typeOf(column: Column) {
  const base = ['integer', 'smallint', 'bigint', 'numeric', 'real', 'double precision'].includes(column.data_type) ? 'number' : column.data_type === 'boolean' ? 'boolean' : ['json','jsonb'].includes(column.data_type) ? 'Json' : 'string';
  return base + (column.is_nullable === 'YES' ? ' | null' : '');
}
type Relation = { table_name: string; constraint_name: string; foreign_table: string; columns: string[]; referenced_columns: string[] };
const { rows: relations } = await db.query<Relation>(`select c.relname as table_name, con.conname as constraint_name,
  f.relname as foreign_table,
  array(select a.attname from unnest(con.conkey) with ordinality k(num,ord) join pg_attribute a on a.attrelid=c.oid and a.attnum=k.num order by k.ord) as columns,
  array(select a.attname from unnest(con.confkey) with ordinality k(num,ord) join pg_attribute a on a.attrelid=f.oid and a.attnum=k.num order by k.ord) as referenced_columns
  from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_class f on f.oid=con.confrelid
  join pg_namespace n on n.oid=c.relnamespace where con.contype='f' and n.nspname='public' order by c.relname,con.conname`);
let output = '// Generated by pnpm db:types from versioned migrations. Do not edit by hand.\n';
output += 'export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n';
output += 'export type Database = {\n  public: {\n    Tables: {\n';
for (const table of tables) {
  const fields = columns.filter((column) => column.table_name === table);
  output += `      ${table}: {\n`;
  for (const kind of ['Row', 'Insert', 'Update']) {
    output += `        ${kind}: {\n`;
    for (const column of fields) {
      const optional = kind === 'Update' || (kind === 'Insert' && (column.column_default !== null || column.is_nullable === 'YES'));
      output += `          ${column.column_name}${optional ? '?' : ''}: ${typeOf(column)};\n`;
    }
    output += '        };\n';
  }
  output += '        Relationships: [\n';
  for (const relation of relations.filter((relation) => relation.table_name === table)) {
    output += `          { foreignKeyName: ${JSON.stringify(relation.constraint_name)}; columns: ${JSON.stringify(relation.columns)}; isOneToOne: false; referencedRelation: ${JSON.stringify(relation.foreign_table)}; referencedColumns: ${JSON.stringify(relation.referenced_columns)} },\n`;
  }
  output += '        ];\n      };\n';
}
type Routine = { name: string; names: string[] | null; types: string[]; defaults: number; returns: string };
const { rows: routines } = await db.query<Routine>(`select p.proname as name, p.proargnames as names,
  array(select format_type(t, null) from unnest(p.proargtypes::oid[]) t) as types,
  p.pronargdefaults as defaults, format_type(p.prorettype, null) as returns
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and (p.proname='is_admin' or p.proname like 'admin_%') order by p.proname`);
const routineType = (type: string) => type === 'void' ? 'undefined' : typeOf({ data_type: type, is_nullable: 'NO' } as Column);
output += '    };\n    Views: Record<string, never>;\n    Functions: {\n';
for (const routine of routines) {
  output += `      ${routine.name}: { Args: `;
  if (!routine.types.length) output += 'Record<string, never>';
  else {
    output += '{ ';
    routine.types.forEach((type, index) => {
      // PostgreSQL accepts explicit NULL arguments; function bodies/constraints validate them.
      output += `${routine.names![index]}${index >= routine.types.length - routine.defaults ? '?' : ''}: ${routineType(type)} | null; `;
    });
    output += '}';
  }
  output += `; Returns: ${routineType(routine.returns)} };\n`;
}
output += '    };\n    Enums: Record<string, never>;\n    CompositeTypes: Record<string, never>;\n  };\n};\n';
await db.close();
const path = 'src/types/database.ts';
if (process.argv.includes('--check')) {
  if (await readFile(path, 'utf8') !== output) throw new Error('Database types are stale. Run pnpm db:types.');
  console.log('Database types match migrations.');
} else {
  await writeFile(path, output);
  console.log(`Generated ${path} from ${tables.length} tables.`);
}
